[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/well-known/assetlinks.json"
  status = 200
 [redirects.headers]
    cache-control = "no-store"

  
[[headers]]
  for = "/well-known/assetlinks.json"
  [headers.values]
    Content-Type = "application/manifest+json"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''
